### ISSUE TITLE
incompatible with firefox 57

### ISSUE THREAD

**Issue by gamboz** [onozaty/firefox-shortcutkey2url#2]
in any case, I wanted to thank you for this extension that I enjoyed a log :-)
ありがとうざいます

**Comment by onozaty** [comment]
I was trying to compatible with Firefox 57. (#1) 
However, due to the following two problems, work was canceled.

* https://bugzilla.mozilla.org/show_bug.cgi?id=1303384
* https://bugzilla.mozilla.org/show_bug.cgi?id=1324255

The problem with Firefox is resolved, i restart work.
It is going to be equivalent to the Chrome version below.

* https://chrome.google.com/webstore/detail/shortcutkey2url-for-chrom/hfohmffbfcobmhfgpkbcjjaijmfplcdg

**Comment by onozaty** [comment]
Implemented at #3
